version: "3.1"

services:
  app:
    build: .
    container_name: api_service
    restart: always
    command: go run ./cmd/server/main.go
    volumes:
      - ./shared_tmp:/armur/repos
    ports:
      - "${APP_PORT}:4500"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_PORT=${APP_PORT}
    env_file:
      - .env
    depends_on:
      - redis_service

  redis_service:
    image: "redis:alpine"
    container_name: redis_service
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
