package reports

import (
	"encoding/json"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// GenerateHTML creates a standalone HTML report from scan results.
func GenerateHTML(taskID string, results map[string]interface{}) (string, error) {
	counts := countFindings(results)
	total := counts["CRITICAL"] + counts["HIGH"] + counts["MEDIUM"] + counts["LOW"] + counts["INFO"]

	findings := flattenFindings(results)

	// Group findings by category
	byCategory := map[string][]map[string]string{}
	for _, f := range findings {
		cat := f["category"]
		byCategory[cat] = append(byCategory[cat], f)
	}

	var categorySections strings.Builder
	for cat, items := range byCategory {
		categorySections.WriteString(fmt.Sprintf(`<div class="category">
<h3>%s <span class="badge">%d</span></h3>
<table>
<thead><tr><th>Severity</th><th>File</th><th>Line</th><th>Message</th><th>CWE</th></tr></thead>
<tbody>`, html.EscapeString(cat), len(items)))

		for _, f := range items {
			sevClass := strings.ToLower(f["severity"])
			categorySections.WriteString(fmt.Sprintf(`
<tr>
  <td><span class="sev %s">%s</span></td>
  <td>%s</td>
  <td>%s</td>
  <td>%s</td>
  <td>%s</td>
</tr>`,
				sevClass,
				html.EscapeString(f["severity"]),
				html.EscapeString(f["file"]),
				html.EscapeString(f["line"]),
				html.EscapeString(f["message"]),
				html.EscapeString(f["cwe"]),
			))
		}
		categorySections.WriteString("</tbody></table></div>")
	}

	report := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Armur Security Report — %s</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }
  h1 { color: #58a6ff; margin-bottom: 0.5rem; }
  h2 { color: #8b949e; font-size: 1rem; margin-bottom: 2rem; }
  h3 { color: #c9d1d9; margin-bottom: 1rem; text-transform: uppercase; font-size: 0.9rem; letter-spacing: 0.05em; }
  .summary { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; text-align: center; min-width: 120px; }
  .card .num { font-size: 2rem; font-weight: bold; }
  .card .label { font-size: 0.8rem; color: #8b949e; }
  .card.critical .num { color: #f85149; }
  .card.high .num { color: #db6d28; }
  .card.medium .num { color: #d29922; }
  .card.low .num { color: #3fb950; }
  .card.info .num { color: #58a6ff; }
  .card.total .num { color: #c9d1d9; }
  .category { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
  .badge { background: #30363d; color: #8b949e; padding: 2px 8px; border-radius: 12px; font-size: 0.8rem; }
  table { width: 100%%; border-collapse: collapse; margin-top: 0.5rem; }
  th { text-align: left; padding: 0.5rem; border-bottom: 1px solid #30363d; color: #8b949e; font-size: 0.8rem; }
  td { padding: 0.5rem; border-bottom: 1px solid #21262d; font-size: 0.85rem; }
  tr:hover { background: #1c2128; }
  .sev { padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }
  .sev.critical { background: #f8514922; color: #f85149; }
  .sev.high { background: #db6d2822; color: #db6d28; }
  .sev.medium { background: #d2992222; color: #d29922; }
  .sev.low { background: #3fb95022; color: #3fb950; }
  .sev.info { background: #58a6ff22; color: #58a6ff; }
  .footer { margin-top: 2rem; color: #484f58; font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
<h1>Armur Security Report</h1>
<h2>Task: %s | Generated: %s</h2>

<div class="summary">
  <div class="card critical"><div class="num">%d</div><div class="label">Critical</div></div>
  <div class="card high"><div class="num">%d</div><div class="label">High</div></div>
  <div class="card medium"><div class="num">%d</div><div class="label">Medium</div></div>
  <div class="card low"><div class="num">%d</div><div class="label">Low</div></div>
  <div class="card info"><div class="num">%d</div><div class="label">Info</div></div>
  <div class="card total"><div class="num">%d</div><div class="label">Total</div></div>
</div>

%s

<div class="footer">Generated by Armur Security Agent</div>
</body>
</html>`,
		html.EscapeString(taskID),
		html.EscapeString(taskID),
		time.Now().Format("2006-01-02 15:04:05"),
		counts["CRITICAL"], counts["HIGH"], counts["MEDIUM"], counts["LOW"], counts["INFO"], total,
		categorySections.String(),
	)

	// Save to ~/.armur/reports/
	dir := filepath.Join(os.Getenv("HOME"), ".armur", "reports")
	os.MkdirAll(dir, 0755)
	path := filepath.Join(dir, taskID+".html")
	if err := os.WriteFile(path, []byte(report), 0644); err != nil {
		return "", fmt.Errorf("failed to write HTML report: %w", err)
	}
	return path, nil
}

// GenerateCSV creates a CSV export from scan results.
func GenerateCSV(taskID string, results map[string]interface{}, outputPath string) (string, error) {
	findings := flattenFindings(results)

	var buf strings.Builder
	buf.WriteString("ID,Category,File,Line,Severity,CWE,Message\n")

	for i, f := range findings {
		buf.WriteString(fmt.Sprintf("%d,%s,%s,%s,%s,%s,%s\n",
			i+1,
			csvEscape(f["category"]),
			csvEscape(f["file"]),
			csvEscape(f["line"]),
			csvEscape(f["severity"]),
			csvEscape(f["cwe"]),
			csvEscape(f["message"]),
		))
	}

	if outputPath == "" {
		dir := filepath.Join(os.Getenv("HOME"), ".armur", "reports")
		os.MkdirAll(dir, 0755)
		outputPath = filepath.Join(dir, taskID+".csv")
	}

	if err := os.WriteFile(outputPath, []byte(buf.String()), 0644); err != nil {
		return "", fmt.Errorf("failed to write CSV report: %w", err)
	}
	return outputPath, nil
}

func csvEscape(s string) string {
	if strings.ContainsAny(s, ",\"\n") {
		return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
	}
	return s
}

// countFindings counts findings by severity across all categories.
func countFindings(results map[string]interface{}) map[string]int {
	counts := map[string]int{"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
	for _, data := range results {
		issues, ok := data.([]interface{})
		if !ok {
			continue
		}
		for _, issue := range issues {
			m, ok := issue.(map[string]interface{})
			if !ok {
				continue
			}
			if sev, ok := m["severity"].(string); ok {
				key := strings.ToUpper(sev)
				if _, exists := counts[key]; exists {
					counts[key]++
				}
			}
			// Check nested files -> issues
			if files, ok := m["files"].([]interface{}); ok {
				for _, file := range files {
					if fm, ok := file.(map[string]interface{}); ok {
						if nested, ok := fm["issues"].([]interface{}); ok {
							for _, ni := range nested {
								if nd, ok := ni.(map[string]interface{}); ok {
									if sev, ok := nd["severity"].(string); ok {
										key := strings.ToUpper(sev)
										if _, exists := counts[key]; exists {
											counts[key]++
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return counts
}

// flattenFindings extracts all findings into a flat list of maps.
func flattenFindings(results map[string]interface{}) []map[string]string {
	var out []map[string]string
	for category, data := range results {
		issues, ok := data.([]interface{})
		if !ok {
			continue
		}
		for _, issue := range issues {
			m, ok := issue.(map[string]interface{})
			if !ok {
				continue
			}
			// Direct finding
			if _, ok := m["message"]; ok {
				out = append(out, map[string]string{
					"category": category,
					"file":     str(m, "path"),
					"line":     str(m, "line"),
					"severity": str(m, "severity"),
					"cwe":      str(m, "cwe"),
					"message":  str(m, "message"),
				})
			}
			// Nested files -> issues structure
			if files, ok := m["files"].([]interface{}); ok {
				cwe := str(m, "cwe")
				for _, file := range files {
					if fm, ok := file.(map[string]interface{}); ok {
						fpath := str(fm, "path")
						if nested, ok := fm["issues"].([]interface{}); ok {
							for _, ni := range nested {
								if nd, ok := ni.(map[string]interface{}); ok {
									out = append(out, map[string]string{
										"category": category,
										"file":     fpath,
										"line":     str(nd, "line"),
										"severity": str(nd, "severity"),
										"cwe":      cwe,
										"message":  str(nd, "message"),
									})
								}
							}
						}
					}
				}
			}
		}
	}
	return out
}

func str(m map[string]interface{}, key string) string {
	if v, ok := m[key]; ok && v != nil {
		switch val := v.(type) {
		case string:
			return val
		case float64:
			return fmt.Sprintf("%d", int(val))
		case json.Number:
			return val.String()
		default:
			return fmt.Sprintf("%v", val)
		}
	}
	return ""
}
